#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Repo Dispatcher

on: 
  # push: 
  #   branches:
  #     - master
  schedule:
    - cron: 30 15 * * *
  watch:
    types: started
  workflow_dispatch:
    inputs:
      packages:
        description: 'Packages'
        required: true
        default: 'luci-app-'

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04
    steps:
    - name: cancel running workflows
      uses: styfle/cancel-workflow-action@main
      with:
        workflow_id: Auto-Package.yml,Repo-Package.yml
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@main
      
    - name: Load Settings.ini
      run: |
        source "${GITHUB_WORKSPACE}/devices/common/settings.ini"
        echo "PACKAGES_REPOS=${PACKAGES_REPOS}" >> $GITHUB_ENV
        
    - name: Trigger matrix Update
      run: |
        gitdate=$(curl -H "Authorization: token ${{ secrets.REPO_TOKEN }}" -s "https://api.github.com/repos/kiddin9/openwrt-packages/commits?&per_page=1" | jq -r '.[0].commit.committer.date')
        fpkg="$(echo "${{github.event.inputs.packages}}" | sed -e 's/\(mipsel_24kc\|x86_64\| [0-9][0-9.]*\| ssh\| noser\| cw\)//g' | sed -e 's/ //g')"
        during="$(echo "${{github.event.inputs.packages}}" | grep -o -E ' [0-9][0-9.]*' | sed -e 's/ //')"
        [[ "$fpkg" && ! "$during" ]] || {
          [ "$during" ] || during="1.05"
          durings=`echo "$during*60*60*24" | bc`
          gitdate=$(date -d "$gitdate" +%s)
          now=$(date -d "$(date)" +%s)
          [ "$during" ] || during="1.05"
          durings=`echo "$during*60*60*24" | bc`
          if [[ $(expr $gitdate + ${durings%.*}) -lt $now ]]; then
            exit;
          fi
        }
        if [[ "${{ github.event.inputs.packages }}" = "mipsel_24kc" ]]; then
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "mipsel_24kc", "client_payload": {"target": "xiaomi_mi-router-3-pro"}}'
        else
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "x86_64 ${{ github.event.inputs.packages }}", "client_payload": {"target": "x86_64"}}'
        fi
