#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Repo Dispatcher

on: 
  # push: 
  #   branches:
  #     - master
  schedule:
    - cron: 30 15 * * *
  watch:
    types: started
  workflow_dispatch:
    inputs:
      packages:
        description: 'Packages'
        required: true
        default: 'luci-app-'

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04
    steps:
    - name: cancel running workflows
      uses: styfle/cancel-workflow-action@main
      with:
        workflow_id: Auto-Package.yml,Repo-Package.yml
        access_token: ${{ github.token }}

    - name: Load Settings.ini
      run: |
        source "${GITHUB_WORKSPACE}/devices/common/settings.ini"
        echo "PACKAGES_REPOS=${PACKAGES_REPOS}" >> $GITHUB_ENV
        
    - name: Trigger matrix Update
      run: |
        if [[ ! "${{ github.event.inputs.packages }}" ]] || [[ "${{ github.event.inputs.packages }}" = "luci-app-" ]]; then
          gitdate=$(curl -H "Authorization: token ${{ secrets.REPO_TOKEN }}" -s "https://api.github.com/repos/${{ env.PACKAGES_REPOS }}/commits?&per_page=1" | jq -r '.[0].commit.committer.date')
          gitdate=$(date -d "$gitdate" +%s)
          now=$(date -d "$(date '+%Y-%m-%d %H:%M:%S')" +%s)
          if [[ $(expr $gitdate + 90000) < $now ]]; then
            exit;
          fi
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "x86_64", "client_payload": {"target": "x86_64"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "mipsel_24kc", "client_payload": {"target": "xiaomi_mi-router-3-pro"}}'
        elif [[ "${{ github.event.inputs.packages }}" = "x86_64" ]]; then
          gitdate=$(curl -H "Authorization: token ${{ secrets.REPO_TOKEN }}" -s "https://api.github.com/repos/${{ env.PACKAGES_REPOS }}/commits?&per_page=1" | jq -r '.[0].commit.committer.date')
          gitdate=$(date -d "$gitdate" +%s)
          now=$(date -d "$(date '+%Y-%m-%d %H:%M:%S')" +%s)
          if [[ $(expr $gitdate + 90000) < $now ]]; then
            exit;
          fi
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "x86_64", "client_payload": {"target": "x86_64"}}'
        elif [[ "${{ github.event.inputs.packages }}" = "mipsel_24kc" ]]; then
          gitdate=$(curl -H "Authorization: token ${{ secrets.REPO_TOKEN }}" -s "https://api.github.com/repos/${{ env.PACKAGES_REPOS }}/commits?&per_page=1" | jq -r '.[0].commit.committer.date')
          gitdate=$(date -d "$gitdate" +%s)
          now=$(date -d "$(date '+%Y-%m-%d %H:%M:%S')" +%s)
          if [[ $(expr $gitdate + 90000) < $now ]]; then
            exit;
          fi
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "mipsel_24kc", "client_payload": {"target": "xiaomi_mi-router-3-pro"}}'
        else
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "${{ github.event.inputs.packages }}", "client_payload": {"target": "x86_64"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "${{ github.event.inputs.packages }}", "client_payload": {"target": "xiaomi_mi-router-3-pro"}}'
        fi
  
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 0

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@master
      continue-on-error: true
      if: env.UPLOAD_FIRMWARE_FOR_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 10
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}    
